service: beer-delivery
provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  environment:
    db: mongodb://mongodb:27017/beer-delivery

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
